### ISSUE TITLE
execution failed

### ISSUE THREAD

**Issue by owen198** [hz-inova/run_jnb#2]
Dear @aplamada :

I'd like to use `run_jnb` to execute the following comment, however, I encounter following error message:
![2018-07-11 12 28 00](https://user-images.githubusercontent.com/16739593/42550811-6ffa5fd4-8506-11e8-8c70-2f19c139cd98.png)

Comment:  `run_jnb joint_example.ipynb -a "{\"TAG_NUMBER\":\"1Y520210100\"}"`
run_jnb Version: 0.1.15 (moreover, I tested 0.1.13 and 0.1.14 as well)
Python Version: 3.6.1

![2018-07-11 1 06 58](https://user-images.githubusercontent.com/16739593/42551745-67120160-850b-11e8-9639-8ae420682243.png)

Thanks,
Owen

**Comment by aplamada** [comment]
Hi @owen198 ,
I tried to reproduce the error based on your input but I did not succed. I guess it is coming from other cells not displayed here. 
Can you please share with me the entire notebook?
Otherwise you can use the END_CELL_INDEX argument with value 5 , i.e. run_jnb ... -M 5, such that only first 5 cells are considered.

**Comment by owen198** [comment]
Dear @aplamada 

I tried to execute commend with argument `-M 5`, it seems work.

However, I observed an additional question: if I add `-M 5`, these means (1) execute first 5 cells only in notebook or (2) replace variables which located in first 5 cells in notebook?

Thanks,
Owen

 

>

**Comment by aplamada** [comment]
Dear @owen198 ,
I am happy to hear this.
You are welcome!

It means (2). Only the variables in the first 5 cells are checked. The entire notebook is executed.
You might try to play with  *possible_parameter* function from the **run_jnb** module to get a better feeling. In the first phase the notebook is parsed and possible parameters are determined. By setting `-M 5` only first 5 cells are checked. The values are replaced and next the entire notebook is executed (if required which is the default option).

By the way. Can you share with me the original notebook? I want to know whether there is a bug in run_jnb module. I expect the error to be related to a multiple variable assignment `a, b = 1, 2`.

**Comment by owen198** [comment]
Dear @aplamada 

Thank you for such quick response and apologize for providing my notebook cause there are too many service connection information in it.

I tried to execute notebook along with removing cells one by one. I found that once if I remove following line, the notebook can be executed success without add `-M 5`:

`x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20) `

for your information~~

Thanks,
Owen

**Comment by aplamada** [comment]
Dear @owen198 ,
Thanks for the hint!
I identified the issue and in the next release it will be addressed. 

Best,
Andrei

**Comment by aplamada** [comment]
Dear @owen198 ,
Can you please give a try to the new version 0.1.16 **without** `-M 5`?
Please let me know your feedback.

Best,
Andrei
